# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: lucas-3691@hotmail.com
author_name: Lucas Santos
has_binder: true
has_settings: false
kind: frontend
labextension_name: runplify
project_short_description: A Jupyter lab extension to save execution output
python_name: runplify
repository: ''
test: true

